version: "3.4"

services:
  pgdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    container_name: "pgdb"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #frontend:
    #build:
      #context: "./frontend"
    #ports:
      #- "3000:3000"
    #volumes:
      #- "./frontend:/home/node/app:delegated"
    #command: "run start"
    #container_name: "frontend"


  #backend:
    #depends_on:
      #- pgdb 
    #build:
      #context: "./backend"
    #ports:
      #- "3001:3000"
    #volumes:
      #- "./backend-node:/home/node/app:delegated"
    #command: "run start"
    #container_name: "backend-node"
